name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-deb-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: |
           sudo apt update && sudo apt install -y aria2 debhelper dpkg-dev build-essential patch bc bison flex libssl-dev libelf-dev git perl python3
                  

      - name: Checkout linux
        run: aria2c https://github.com/NekoSekaiMoe/asus_linux_debian_test/releases/download/v1/src.tar.xz && mkdir -p -v src && tar -xf src.tar.xz -C src

      - name: Ccache for gh actions
        uses: hendrikmuhs/ccache-action@v1.2.13
        with:
          key: ee2b31d23ae6068c6aecc2e81e4b71c40ed72654

      - name: Configure
        run: |
          cd src
          ls
          make asus_defconfig
          bash config.sh

      - name: build
        env:
          CC: "ccache gcc"
          ARCH: "x86"
        run: |
          cd src
          export USE_CCACHE=1
          make -j8 deb-pkg
          
      - name: Commit updates
        run: ls 
