name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-deb-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: rokibhasansagar/slimhub_actions@main
      - name: Install Build Tools
        run: |
           sudo apt update && sudo apt install -y aria2 debhelper dpkg-dev build-essential patch bc bison flex libssl-dev libelf-dev git perl python3
                  
      - name: Checkout linux
        run: aria2c https://github.com/NekoSekaiMoe/asus_linux_debian_test/releases/download/v1/src.tar.xz && mkdir -p -v src && tar -xf src.tar.xz

      - name: Ccache for gh actions
        uses: hendrikmuhs/ccache-action@v1.2.13
        with:
          max-size: 8192M
          key: ee2b31d23ae6068c6aecc2e81e4b71c40ed72654

      - name: Configure
        run: |
          cd src
          make asus_defconfig
          bash config.sh

      - name: build
        env:
          CC: "ccache gcc"
        run: |
          cd src
          export USE_CCACHE=1
          make -j8 bindeb-pkg LOCALVERSION=-asud_linux_g14
          
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./*.deb
