name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-deb-amd64:
    container: debian:trixie
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: |
          echo "deb-src http://deb.debian.org/debian/ trixie main contrib non-free" | tee -a /etc/apt/sources.list >/dev/null
          apt update && apt install -y debhelper dpkg-dev build-essential patch bc bison flex libssl-dev libelf-dev git perl python3
                  

      - name: Checkout linux
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.9

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Ccache for gh actions
        uses: hendrikmuhs/ccache-action@v1.2.13
        with:
          key: ee2b31d23ae6068c6aecc2e81e4b71c40ed72654
            
      - name: patch
        run: |
          cd linux
          git clone https://salsa.debian.org/kernel-team/linux/ deb --depth=1
          git apply deb/debian/patches/*.patch
          mv linux/* .
          git apply ../patches/*.patch
          mv ../asus_defconfig ./arch/x86/configs/

      - name: Configure
        run: |
          cd linux
          make asus_defconfig
          bash ../patch.sh

      - name: build
        env:
          CC: "ccache gcc"
        run: |
          cd linux
          export USE_CCACHE=1
          make -j8 
          
      - name: Package
        env:
          CC: "ccache gcc"
        run: |
          cd linux
          export USE_CCACHE=1
          make -j8 deb-pkg V=1
